import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Plus,
  Edit,
  Trash2,
  Eye,
  Globe,
  FileText,
  Clock,
  Calendar,
  Rss,
  ExternalLink,
  BookOpen,
} from "lucide-react";
import { toast } from "sonner";
import { Label } from "@/components/ui/label";

type BlogPost = {
  id: number;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  category: string | null;
  tags: string | null;
  author: string | null;
  status: "draft" | "published";
  readingTimeMinutes: number | null;
  publishedAt: Date | null;
  isAutoGenerated: boolean | null;
  createdAt: Date;
  updatedAt: Date;
};

type PostForm = {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  category: string;
  tags: string;
  author: string;
  readingTimeMinutes: number;
  status: "draft" | "published";
};

const emptyForm: PostForm = {
  title: "",
  slug: "",
  excerpt: "",
  content: "",
  category: "",
  tags: "",
  author: "Lynx AI Team",
  readingTimeMinutes: 5,
  status: "draft",
};

function slugify(text: string) {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
}

function formatDate(date: Date | string | null) {
  if (!date) return "—";
  return new Date(date).toLocaleDateString("es-ES", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export default function DashboardBlog() {
  const { user } = useAuth();
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();

  const [showForm, setShowForm] = useState(false);
  const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
  const [deletePost, setDeletePost] = useState<BlogPost | null>(null);
  const [form, setForm] = useState<PostForm>(emptyForm);
  const [previewPost, setPreviewPost] = useState<BlogPost | null>(null);

  const { data: posts, isLoading } = trpc.blog.adminList.useQuery();

  const createMutation = trpc.blog.create.useMutation({
    onSuccess: () => {
      toast.success("Artículo creado correctamente");
      utils.blog.adminList.invalidate();
      utils.blog.list.invalidate();
      setShowForm(false);
      setForm(emptyForm);
    },
    onError: (e) => toast.error(e.message),
  });

  const updateMutation = trpc.blog.update.useMutation({
    onSuccess: () => {
      toast.success("Artículo actualizado");
      utils.blog.adminList.invalidate();
      utils.blog.list.invalidate();
      setShowForm(false);
      setEditingPost(null);
      setForm(emptyForm);
    },
    onError: (e) => toast.error(e.message),
  });

  const publishMutation = trpc.blog.publish.useMutation({
    onSuccess: () => {
      toast.success("Artículo publicado");
      utils.blog.adminList.invalidate();
      utils.blog.list.invalidate();
    },
    onError: (e) => toast.error(e.message),
  });

  const deleteMutation = trpc.blog.delete.useMutation({
    onSuccess: () => {
      toast.success("Artículo eliminado");
      utils.blog.adminList.invalidate();
      utils.blog.list.invalidate();
      setDeletePost(null);
    },
    onError: (e) => toast.error(e.message),
  });

  // Redirect non-admins
  if (user && user.role !== "admin") {
    navigate("/dashboard");
    return null;
  }

  function openCreate() {
    setEditingPost(null);
    setForm(emptyForm);
    setShowForm(true);
  }

  function openEdit(post: BlogPost) {
    setEditingPost(post);
    setForm({
      title: post.title,
      slug: post.slug,
      excerpt: post.excerpt ?? "",
      content: post.content,
      category: post.category ?? "",
      tags: post.tags ? (JSON.parse(post.tags) as string[]).join(", ") : "",
      author: post.author ?? "Lynx AI Team",
      readingTimeMinutes: post.readingTimeMinutes ?? 5,
      status: post.status,
    });
    setShowForm(true);
  }

  function handleTitleChange(title: string) {
    setForm((f) => ({
      ...f,
      title,
      slug: editingPost ? f.slug : slugify(title),
    }));
  }

  function handleSubmit() {
    if (!form.title.trim() || !form.content.trim()) {
      toast.error("El título y el contenido son obligatorios");
      return;
    }
    const tags = form.tags
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);

    if (editingPost) {
      updateMutation.mutate({
        id: editingPost.id,
        title: form.title,
        slug: form.slug,
        excerpt: form.excerpt || undefined,
        content: form.content,
        category: form.category || undefined,
        tags,
        author: form.author || undefined,
        readingTimeMinutes: form.readingTimeMinutes,
        status: form.status,
      });
    } else {
      createMutation.mutate({
        title: form.title,
        slug: form.slug || slugify(form.title),
        excerpt: form.excerpt || undefined,
        content: form.content,
        category: form.category || undefined,
        tags,
        author: form.author || undefined,
        readingTimeMinutes: form.readingTimeMinutes,
        status: form.status,
      });
    }
  }

  const isSaving = createMutation.isPending || updateMutation.isPending;

  return (
    <DashboardLayout>
      <div className="p-6 max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <BookOpen className="w-6 h-6 text-primary" />
              Blog
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              Gestiona los artículos del blog de Lynx AI
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" asChild>
              <a href="/blog" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                <ExternalLink className="w-4 h-4" />
                Ver blog
              </a>
            </Button>
            <Button onClick={openCreate} className="lynx-gradient text-white border-0">
              <Plus className="w-4 h-4 mr-2" />
              Nuevo artículo
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          {[
            { label: "Total artículos", value: posts?.length ?? 0, icon: FileText },
            { label: "Publicados", value: posts?.filter((p) => p.status === "published").length ?? 0, icon: Globe },
            { label: "Borradores", value: posts?.filter((p) => p.status === "draft").length ?? 0, icon: FileText },
          ].map(({ label, value, icon: Icon }) => (
            <div key={label} className="rounded-xl border border-border/50 bg-card p-4">
              <div className="flex items-center gap-2 text-muted-foreground mb-1">
                <Icon className="w-4 h-4" />
                <span className="text-xs">{label}</span>
              </div>
              <p className="text-2xl font-bold">{value}</p>
            </div>
          ))}
        </div>

        {/* Posts list */}
        {isLoading ? (
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="rounded-xl border border-border/50 bg-card p-5 animate-pulse">
                <div className="h-5 bg-muted/50 rounded w-1/2 mb-2" />
                <div className="h-4 bg-muted/50 rounded w-3/4" />
              </div>
            ))}
          </div>
        ) : !posts || posts.length === 0 ? (
          <div className="text-center py-16 rounded-xl border border-border/50 bg-card">
            <BookOpen className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
            <h3 className="font-semibold mb-1">No hay artículos todavía</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Crea tu primer artículo o espera a que la IA genere uno automáticamente.
            </p>
            <Button onClick={openCreate} variant="outline">
              <Plus className="w-4 h-4 mr-2" />
              Crear artículo
            </Button>
          </div>
        ) : (
          <div className="space-y-3">
            {posts.map((post) => (
              <div
                key={post.id}
                className="rounded-xl border border-border/50 bg-card p-5 flex items-start gap-4 hover:border-primary/20 transition-colors"
              >
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <h3 className="font-semibold text-sm truncate">{post.title}</h3>
                    <Badge
                      variant={post.status === "published" ? "default" : "secondary"}
                      className={`text-xs shrink-0 ${post.status === "published" ? "bg-green-500/20 text-green-600 border-green-500/30" : ""}`}
                    >
                      {post.status === "published" ? "Publicado" : "Borrador"}
                    </Badge>
                    {post.isAutoGenerated && (
                      <Badge variant="outline" className="text-xs shrink-0 text-primary border-primary/30">
                        <Rss className="w-3 h-3 mr-1" />
                        Auto
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground line-clamp-1 mb-2">
                    {post.excerpt ?? post.content.replace(/<[^>]+>/g, "").slice(0, 120)}
                  </p>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {post.status === "published" ? formatDate(post.publishedAt) : formatDate(post.createdAt)}
                    </span>
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      {post.readingTimeMinutes ?? 5} min
                    </span>
                    {post.category && (
                      <span className="text-primary">{post.category}</span>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  {post.status === "published" && (
                    <Button
                      size="sm"
                      variant="ghost"
                      className="h-8 w-8 p-0"
                      asChild
                    >
                      <a href={`/blog/${post.slug}`} target="_blank" rel="noopener noreferrer">
                        <Eye className="w-4 h-4" />
                      </a>
                    </Button>
                  )}
                  {post.status === "draft" && (
                    <Button
                      size="sm"
                      variant="outline"
                      className="h-8 text-xs"
                      onClick={() => publishMutation.mutate({ id: post.id })}
                      disabled={publishMutation.isPending}
                    >
                      <Globe className="w-3 h-3 mr-1" />
                      Publicar
                    </Button>
                  )}
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-8 w-8 p-0"
                    onClick={() => openEdit(post as BlogPost)}
                  >
                    <Edit className="w-4 h-4" />
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                    onClick={() => setDeletePost(post as BlogPost)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Create/Edit Dialog */}
      <Dialog open={showForm} onOpenChange={(v) => { if (!v) { setShowForm(false); setEditingPost(null); setForm(emptyForm); } }}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {editingPost ? "Editar artículo" : "Nuevo artículo"}
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <Label>Título *</Label>
                <Input
                  placeholder="Título del artículo"
                  value={form.title}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  className="mt-1"
                />
              </div>

              <div className="col-span-2">
                <Label>Slug (URL)</Label>
                <Input
                  placeholder="url-del-articulo"
                  value={form.slug}
                  onChange={(e) => setForm((f) => ({ ...f, slug: e.target.value }))}
                  className="mt-1 font-mono text-sm"
                />
                <p className="text-xs text-muted-foreground mt-1">
                  URL: lynxaiassistant.com/blog/{form.slug || "..."}
                </p>
              </div>

              <div>
                <Label>Categoría</Label>
                <Input
                  placeholder="ej: Ventas & IA"
                  value={form.category}
                  onChange={(e) => setForm((f) => ({ ...f, category: e.target.value }))}
                  className="mt-1"
                />
              </div>

              <div>
                <Label>Autor</Label>
                <Input
                  placeholder="Nombre del autor"
                  value={form.author}
                  onChange={(e) => setForm((f) => ({ ...f, author: e.target.value }))}
                  className="mt-1"
                />
              </div>

              <div>
                <Label>Tiempo de lectura (minutos)</Label>
                <Input
                  type="number"
                  min={1}
                  max={60}
                  value={form.readingTimeMinutes}
                  onChange={(e) => setForm((f) => ({ ...f, readingTimeMinutes: Number(e.target.value) }))}
                  className="mt-1"
                />
              </div>

              <div>
                <Label>Estado</Label>
                <select
                  value={form.status}
                  onChange={(e) => setForm((f) => ({ ...f, status: e.target.value as "draft" | "published" }))}
                  className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                >
                  <option value="draft">Borrador</option>
                  <option value="published">Publicado</option>
                </select>
              </div>

              <div className="col-span-2">
                <Label>Extracto (resumen)</Label>
                <Textarea
                  placeholder="Breve descripción del artículo (máx. 160 caracteres para SEO)"
                  value={form.excerpt}
                  onChange={(e) => setForm((f) => ({ ...f, excerpt: e.target.value }))}
                  className="mt-1 resize-none"
                  rows={2}
                  maxLength={500}
                />
              </div>

              <div className="col-span-2">
                <Label>Tags (separados por coma)</Label>
                <Input
                  placeholder="ej: inteligencia artificial, ventas, chatbot"
                  value={form.tags}
                  onChange={(e) => setForm((f) => ({ ...f, tags: e.target.value }))}
                  className="mt-1"
                />
              </div>

              <div className="col-span-2">
                <Label>Contenido (HTML) *</Label>
                <Textarea
                  placeholder="<h2>Introducción</h2><p>...</p>"
                  value={form.content}
                  onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))}
                  className="mt-1 font-mono text-xs resize-y"
                  rows={16}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Puedes usar HTML semántico: &lt;h2&gt;, &lt;h3&gt;, &lt;p&gt;, &lt;ul&gt;, &lt;li&gt;, &lt;strong&gt;, &lt;blockquote&gt;
                </p>
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => { setShowForm(false); setEditingPost(null); setForm(emptyForm); }}>
              Cancelar
            </Button>
            <Button onClick={handleSubmit} disabled={isSaving} className="lynx-gradient text-white border-0">
              {isSaving ? "Guardando..." : editingPost ? "Guardar cambios" : "Crear artículo"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete confirmation */}
      <AlertDialog open={!!deletePost} onOpenChange={(v) => { if (!v) setDeletePost(null); }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>¿Eliminar artículo?</AlertDialogTitle>
            <AlertDialogDescription>
              Esta acción no se puede deshacer. El artículo "{deletePost?.title}" será eliminado permanentemente.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => deletePost && deleteMutation.mutate({ id: deletePost.id })}
            >
              Eliminar
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </DashboardLayout>
  );
}
