CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(256) NOT NULL,
	`title` varchar(512) NOT NULL,
	`excerpt` text NOT NULL,
	`content` text NOT NULL,
	`coverImageUrl` text,
	`category` varchar(128) DEFAULT 'General',
	`tags` json DEFAULT ('[]'),
	`author` varchar(128) DEFAULT 'Lynx AI Team',
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`isAutoGenerated` boolean NOT NULL DEFAULT false,
	`readingTimeMinutes` int DEFAULT 5,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
