import { motion } from "framer-motion";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Clock, Calendar, ArrowRight, BookOpen, Rss } from "lucide-react";
import { trpc } from "@/lib/trpc";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

function formatDate(date: Date | string | null) {
  if (!date) return "";
  return new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function BlogCard({ post, index }: { post: any; index: number }) {
  const isFirst = index === 0;

  return (
    <motion.article
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.1, duration: 0.5 }}
      className={`group ${isFirst ? "md:col-span-2" : ""}`}
    >
      <Link href={`/blog/${post.slug}`} className="block h-full">
        <div className="h-full rounded-2xl border border-border/50 bg-card overflow-hidden hover:border-primary/30 hover:shadow-lg hover:shadow-primary/5 transition-all duration-300">
          {/* Cover image */}
          <div className={`relative overflow-hidden ${isFirst ? "h-56" : "h-44"} bg-gradient-to-br from-primary/10 via-violet-500/10 to-blue-500/10`}>
            {post.coverImageUrl ? (
              <img
                src={post.coverImageUrl}
                alt={post.title}
                className="absolute inset-0 w-full h-full object-cover"
                loading="lazy"
              />
            ) : (
              <div className="absolute inset-0 flex items-center justify-center">
                <BookOpen className="w-16 h-16 text-primary/20" />
              </div>
            )}
            {/* Category badge */}
            <div className="absolute top-4 left-4">
              <Badge variant="secondary" className="bg-background/80 backdrop-blur-sm text-xs font-medium">
                {post.category || "General"}
              </Badge>
            </div>
            {post.isAutoGenerated && (
              <div className="absolute top-4 right-4">
                <Badge className="bg-primary/80 text-white text-xs">
                  <Rss className="w-3 h-3 mr-1" />
                  Auto
                </Badge>
              </div>
            )}
          </div>

          {/* Content */}
          <div className="p-6">
            <h2 className={`font-bold mb-3 group-hover:text-primary transition-colors leading-tight ${isFirst ? "text-2xl" : "text-lg"}`}>
              {post.title}
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed mb-5 line-clamp-3">
              {post.excerpt}
            </p>

            {/* Meta */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <span className="flex items-center gap-1.5">
                  <Calendar className="w-3.5 h-3.5" />
                  {formatDate(post.publishedAt)}
                </span>
                <span className="flex items-center gap-1.5">
                  <Clock className="w-3.5 h-3.5" />
                  {post.readingTimeMinutes} min read
                </span>
              </div>
              <span className="text-xs text-primary font-medium flex items-center gap-1 group-hover:gap-2 transition-all">
                Read more <ArrowRight className="w-3 h-3" />
              </span>
            </div>
          </div>
        </div>
      </Link>
    </motion.article>
  );
}

export default function BlogPage() {
  const { data: posts, isLoading } = trpc.blog.list.useQuery({ limit: 20 });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />

      {/* Hero */}
      <section className="pt-32 pb-16 px-4 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
        >
          <Badge variant="outline" className="mb-6 text-primary border-primary/30 bg-primary/5 px-4 py-1.5">
            <Rss className="w-3.5 h-3.5 mr-2" />
            Lynx AI Blog
          </Badge>
          <h1 className="text-5xl sm:text-6xl font-bold tracking-tight mb-6 max-w-3xl mx-auto">
            Insights on{" "}
            <span className="bg-gradient-to-r from-blue-500 to-violet-500 bg-clip-text text-transparent">
              AI & Business
            </span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Articles, guides, and use cases on artificial intelligence for businesses. Published weekly by our team.
          </p>
        </motion.div>
      </section>

      {/* Articles grid */}
      <section className="pb-24 px-4">
        <div className="max-w-5xl mx-auto">
          {isLoading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {[...Array(4)].map((_, i) => (
                <div key={i} className="rounded-2xl border border-border/50 bg-card overflow-hidden animate-pulse">
                  <div className="h-44 bg-muted/50" />
                  <div className="p-6 space-y-3">
                    <div className="h-5 bg-muted/50 rounded w-3/4" />
                    <div className="h-4 bg-muted/50 rounded w-full" />
                    <div className="h-4 bg-muted/50 rounded w-2/3" />
                  </div>
                </div>
              ))}
            </div>
          ) : !posts || posts.length === 0 ? (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-24"
            >
              <BookOpen className="w-16 h-16 text-muted-foreground/30 mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">Coming soon</h3>
              <p className="text-muted-foreground">
                We're preparing amazing content about AI and business. Check back soon!
              </p>
            </motion.div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {posts.map((post, i) => (
                <BlogCard key={post.id} post={post} index={i} />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 px-4 bg-muted/20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="max-w-2xl mx-auto text-center"
        >
          <h2 className="text-2xl font-bold mb-3">Want an AI chatbot on your website?</h2>
          <p className="text-muted-foreground mb-6">
            Get started for free today and transform your visitors' experience with AI.
          </p>
          <Link href="/register">
            <Button size="lg" className="lynx-gradient text-white border-0 shadow-lg hover:opacity-90 px-8 font-semibold">
              Start free — 14 days
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </Link>
        </motion.div>
      </section>

      <Footer />
    </div>
  );
}
