import type { Request, Response } from "express";
import { getDb } from "./db";
import { blogPosts } from "../drizzle/schema";
import { sdk } from "./_core/sdk";

/**
 * POST /api/scheduled/auto-blog
 *
 * Called by the AGENT cron every week. The agent generates a full blog article
 * and POSTs it here as JSON. No SDK auth needed — the agent uses the
 * $SCHEDULED_TASK_COOKIE env var injected by the platform.
 *
 * Body shape:
 * {
 *   title: string,
 *   slug: string,
 *   excerpt: string,
 *   content: string,       // HTML
 *   category: string,
 *   tags: string[],
 *   author: string,
 *   readingTimeMinutes: number,
 * }
 */
export async function autoBlogHandler(req: Request, res: Response) {
  try {
    // ── Auth: only Manus scheduled cron tasks may call this endpoint ──────
    let caller;
    try {
      caller = await sdk.authenticateRequest(req);
    } catch {
      return res.status(401).json({ error: "Unauthorized" });
    }
    if (!caller.isCron) {
      return res.status(403).json({ error: "Forbidden: only cron tasks may call this endpoint" });
    }

    const {
      title,
      slug,
      excerpt,
      content,
      category,
      tags,
      author,
      readingTimeMinutes,
    } = req.body as {
      title?: string;
      slug?: string;
      excerpt?: string;
      content?: string;
      category?: string;
      tags?: string[];
      author?: string;
      readingTimeMinutes?: number;
    };

    if (!title || !slug || !content) {
      return res.status(400).json({ error: "Missing required fields: title, slug, content" });
    }

    const db = await getDb();
    if (!db) {
      return res.status(500).json({ error: "Database unavailable" });
    }

    const cleanSlug = String(slug)
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-")
      .slice(0, 255);

    const insertData = {
      title: String(title).slice(0, 512),
      slug: cleanSlug,
      excerpt: excerpt ? String(excerpt).slice(0, 500) : "",
      content: String(content),
      category: category ? String(category).slice(0, 128) : "Artificial Intelligence",
      tags: tags && Array.isArray(tags) ? tags : [],
      author: author ? String(author).slice(0, 128) : "Lynx AI Team",
      readingTimeMinutes: readingTimeMinutes ? Number(readingTimeMinutes) : 7,
      status: "published" as const,
      publishedAt: new Date(),
      isAutoGenerated: true,
    };

    await db.insert(blogPosts).values(insertData);

    console.log(`[AutoBlog] Published new article: "${title}" (slug: ${slug})`);
    return res.json({ ok: true, title, slug });
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    const stack = err instanceof Error ? err.stack : undefined;
    console.error("[AutoBlog] Error:", error);
    return res.status(500).json({
      error,
      stack,
      context: { url: req.url },
      timestamp: new Date().toISOString(),
    });
  }
}
